# -*- coding: utf-8 -*-
"""forecasting stock control xg boost and reglin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkkxqhaZyNqoo3lNiF82DDvlKI0Sk0Q-

# **📦 DEMAND FORECASTING & INVENTORY OPTIMIZATION**

# IMPORT LIBRARY
"""

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

from datetime import timedelta
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from scipy.stats import norm

"""# LOAD & CLEAN DATA




"""

import pandas as pd

def load_and_clean(path):
    df = pd.read_excel(path)

    df = df.rename(columns={
        'Date': 'date',
        'Item Code': 'sku',
        'Item Name': 'product_name',
        'Unit Sold': 'units_sold',
        'SOH': 'stock_on_hand' # Add this line to rename 'SOH' to 'stock_on_hand'
    })

    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values(['sku', 'date'])

    return df

"""# 2. FEATURE ENGINEERING"""

def create_features(df):
    df = df.copy()

    df['day_of_week'] = df['date'].dt.dayofweek
    df['month'] = df['date'].dt.month

    for lag in [1, 7, 14]:
        df[f'lag_{lag}'] = df.groupby('sku')['units_sold'].shift(lag)

    df['rolling_7'] = df.groupby('sku')['units_sold'].rolling(7).mean().reset_index(0, drop=True)
    df['rolling_14'] = df.groupby('sku')['units_sold'].rolling(14).mean().reset_index(0, drop=True)

    return df.dropna()

"""# MODEL TRAINING"""

from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error

def train_model(X_train, y_train):
    model = XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42
    )
    model.fit(X_train, y_train)
    return model

"""# 4. FORECAST 30 HARI"""

def forecast_next_30_days(model, temp, features):
    last_date = temp['date'].iloc[-1]

    future_dates = [
        last_date + timedelta(days=i)
        for i in range(1, 31)
    ]

    future_df = pd.DataFrame({
        'day_of_week': [d.dayofweek for d in future_dates],
        'month': [d.month for d in future_dates],
        'lag_1': temp['units_sold'].iloc[-1],
        'lag_7': temp['units_sold'].iloc[-7],
        'lag_14': temp['units_sold'].iloc[-14],
        'rolling_7': temp['rolling_7'].iloc[-1],
        'rolling_14': temp['rolling_14'].iloc[-1]
    })

    forecast = model.predict(future_df[features])
    forecast = np.clip(forecast, 0, None)

    return future_dates, forecast

"""# INVENTORY METRICS"""

def inventory_metrics(forecast, current_stock, lead_time=3, service_level=0.95):
    avg_demand = forecast.mean()
    demand_std = forecast.std()

    z = norm.ppf(service_level)

    safety_stock = z * demand_std * np.sqrt(lead_time)
    reorder_point = avg_demand * lead_time + safety_stock
    restock_needed = max(0, reorder_point - current_stock)

    return {
        "avg_daily_demand": round(avg_demand, 2),
        "safety_stock": round(safety_stock),
        "reorder_point": round(reorder_point),
        "restock_needed": round(restock_needed)
    }

"""# VISUALISASI INVENTORY"""

def plot_inventory(temp, future_dates, forecast, inventory, product_name):
    plt.figure(figsize=(12,4))

    plt.plot(temp['date'], temp['units_sold'], label='Actual', alpha=0.7)
    plt.plot(future_dates, forecast, '--', label='Forecast')

    plt.axhline(
        inventory['reorder_point'],
        linestyle=':',
        color='red',
        label='Reorder Point'
    )

    plt.title(f'Inventory Optimization — {product_name}')
    plt.ylabel('Units Sold')
    plt.legend()
    plt.grid(True)
    plt.show()

"""# MAIN PIPELINE (RUNNER)"""

from sklearn.model_selection import train_test_split

# ====================================
# LOAD DATA
# ====================================
df = load_and_clean("/content/Data_Stock.xlsx")
df = create_features(df)

features = [
    'day_of_week', 'month',
    'lag_1', 'lag_7', 'lag_14',
    'rolling_7', 'rolling_14'
]

inventory_results = []

# ====================================
# LOOP PER SKU
# ====================================
for sku in df['sku'].unique():

    temp = df[df['sku'] == sku].copy()

    if len(temp) < 30:
        continue

    X = temp[features]
    y = temp['units_sold']

    X_train, _, y_train, _ = train_test_split(
        X, y, test_size=0.2, shuffle=False
    )

    model = train_model(X_train, y_train)

    future_dates, forecast = forecast_next_30_days(
        model, temp, features
    )

    current_stock = temp['stock_on_hand'].iloc[-1]

    inventory = inventory_metrics(
        forecast=forecast,
        current_stock=current_stock
    )

    product_name = temp['product_name'].iloc[0]

    plot_inventory(
        temp, future_dates, forecast,
        inventory, product_name
    )

    inventory_results.append({
        "sku": sku,
        "product_name": product_name,
        "current_stock": current_stock,
        **inventory
    })

    print(f"✅ Processed SKU: {sku}")

df.groupby('sku').size().max()

"""# RANKING & STOCK CLASSIFICATION"""

inventory_df = pd.DataFrame(inventory_results)

inventory_df['avg_daily_demand'] = inventory_df['avg_daily_demand'].replace(0, np.nan)

inventory_df['urgency_score'] = (
    inventory_df['restock_needed'] /
    inventory_df['avg_daily_demand']
).replace([np.inf, -np.inf, np.nan], 0)

inventory_df = inventory_df.sort_values(
    'urgency_score',
    ascending=False
).reset_index(drop=True)

inventory_df['urgency_rank'] = inventory_df.index + 1

# FAST / SLOW / DEAD
p70 = inventory_df['avg_daily_demand'].quantile(0.7)
p30 = inventory_df['avg_daily_demand'].quantile(0.3)

inventory_df['stock_category'] = inventory_df['avg_daily_demand'].apply(
    lambda d: 'FAST' if d >= p70 else 'SLOW' if d >= p30 else 'DEAD'
)

"""# EXECUTIVE SUMMARY"""

summary = {
    "total_sku": inventory_df.shape[0],
    "urgent_sku": (inventory_df['restock_needed'] > 0).sum(),
    "fast_moving": (inventory_df['stock_category'] == 'FAST').sum(),
    "slow_moving": (inventory_df['stock_category'] == 'SLOW').sum(),
    "dead_stock": (inventory_df['stock_category'] == 'DEAD').sum(),
    "avg_restock_qty": round(inventory_df['restock_needed'].mean(), 2)
}

summary_df = pd.DataFrame.from_dict(
    summary, orient='index', columns=['value']
)

summary_df

"""Berdasarkan hasil analisis 200 SKU, berikut adalah gambaran kesehatan inventory portofolio kamu:

Ringkasan Angka

Total SKU: 200

Urgent SKU: 66

Fast Moving: 60

Slow Moving: 80

Dead Stock: 60

Rata-rata Restock Quantity: 31 unit

Analisis menunjukkan bahwa risiko inventory tidak tersebar merata. Sekitar sepertiga SKU membutuhkan perhatian segera, sementara hampir sepertiga lainnya justru tidak memberikan kontribusi signifikan. Dengan memfokuskan replenishment pada SKU fast-moving dan urgent, perusahaan dapat meningkatkan service level sekaligus mengoptimalkan cashflow.

# SAVE OUTPUT
"""

os.makedirs("data/output", exist_ok=True)

inventory_df.to_excel(
    "data/output/inventory_optimization_output.xlsx",
    index=False
)

print("🎉 Inventory optimization completed & saved")

from google.colab import drive
drive.mount('/content/drive')

"""1️⃣ RANKING SKU PALING URGENT (REORDER PRIORITY)
📌 Konsep

SKU paling urgent =


*   restock_needed paling besar
*   stok sekarang < reorder point
*   demand tinggi

📐 Formula Urgency Score
urgency_score = restock_needed / avg_daily_demand

2️⃣ FAST / SLOW / DEAD STOCK
📌 Definisi Profesional
Kategori	    Kriteria
Fast Moving	  avg_daily_demand ≥ P70
Slow Moving	  P30 ≤ demand < P70
Dead Stock	  avg_daily_demand < P30
"""

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

# URGENCY REORDER
top_15 = inventory_df.head(15)

plt.figure(figsize=(10,6))
sns.barplot(
    data=top_15,
    x='urgency_score',
    y='product_name',
    palette='Reds_r'
)

plt.title("Top 15 Most Urgent SKUs to Reorder")
plt.xlabel("Urgency Score")
plt.ylabel("Product")
plt.tight_layout()
plt.show()

"""Grafik ini menampilkan 15 SKU dengan tingkat urgensi reorder tertinggi, yang dihitung berdasarkan:

Urgency Score = Restock Needed ÷ Average Daily Demand

Semakin besar nilainya, semakin kritis SKU tersebut untuk segera dilakukan pemesanan ulang.
"""

# FAST / SLOW / DEAD STOCK DISTRIBUTION
plt.figure(figsize=(6,6))
inventory_df['stock_category'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%',
    startangle=90,
    colors=['green', 'orange', 'red']
)

plt.title("Inventory Portfolio Composition")
plt.ylabel("")
plt.show()

"""**Fast Moving masih relatif sehat (30%)**

📌 60 SKU masuk kategori FAST.

Makna bisnis:

SKU ini adalah Kontributor utama penjualan yang harus diprioritaskan dalam replenishment. Namun, jika tidak dijaga stoknya → langsung berdampak ke revenue.

-> FAST + urgent = prioritas tertinggi procurement

**40% SKU adalah Slow Moving (zona peluang)**

📌 80 SKU bergerak moderat.

Makna bisnis:

Bukan masalah, tapi belum optimal

Potensi yang bisa dilakukan adalah melakukan Promo selektif, Optimasi, harga / bundling, Penyesuaian safety stock

-> Dengan strategi tepat, sebagian bisa “naik kelas” jadi FAST.

**30% Dead Stock = sinyal peringatan**

📌 60 SKU hampir tidak berkontribusi ke demand.

Risiko utama: Modal tertahan, Biaya penyimpanan, Risiko waste (terutama produk fresh)

-> Kandidat kuat untuk:

- Clearance
- Delisting
- Stop reorder
"""

# DEMAND vs STOCK
plt.figure(figsize=(8,6))

sns.scatterplot(
    data=inventory_df,
    x='avg_daily_demand',
    y='current_stock',
    hue='stock_category',
    palette={'FAST':'green','SLOW':'orange','DEAD':'red'},
    alpha=0.7
)

plt.axline((0,0),(1,1), linestyle='--', color='gray')
plt.title("Demand vs Current Stock")
plt.xlabel("Average Daily Demand")
plt.ylabel("Current Stock")
plt.legend(title="Stock Category")
plt.show()

"""Grafik ini menunjukkan bahwa sebagian besar risiko inventory bukan hanya kekurangan stok, tetapi justru overstock pada SKU dengan demand rendah. Dengan realokasi stok dari dead dan slow moving ke fast moving SKU, perusahaan dapat meningkatkan inventory turnover dan mengurangi capital lock-in.

Demand vs Current Stock

Grafik ini memetakan hubungan antara rata-rata demand harian (X-axis) dan stok saat ini (Y-axis) untuk setiap SKU, dengan warna menunjukkan kategori pergerakan stok:

🟢 FAST – demand tinggi

🟠 SLOW – demand menengah

🔴 DEAD – demand rendah

Garis putus-putus menunjukkan rasio ideal antara demand dan stok (indikasi keseimbangan).

🔎 Temuan Utama (Key Insights)
1️⃣ Banyak SKU berada di zona overstock

Terutama:

🔴 DEAD

🟠 SLOW

Ciri:

Demand rendah

Stok relatif tinggi

Dampak:

Modal tertahan

Biaya penyimpanan meningkat

Risiko waste (khusus produk fresh)

2️⃣ FAST moving SKU relatif lebih seimbang, tapi belum ideal

🟢 FAST cenderung:

Demand tinggi

Stok juga tinggi

Namun:

Sebagian berada di bawah garis ideal

Mengindikasikan risiko stock-out jika demand naik tiba-tiba

3️⃣ DEAD stock sangat jelas terpisah

🔴 DEAD terkonsentrasi di:

Demand < 40

Stok 100–450

Ini sinyal kuat:

SKU tidak lagi relevan dengan kebutuhan pasar
"""

# RESTOCK NEEDED DISTRIBUTION
plt.figure(figsize=(8,5))
sns.histplot(
    inventory_df['restock_needed'],
    bins=30,
    kde=True
)

plt.title("Distribution of Restock Quantity")
plt.xlabel("Restock Needed")
plt.show()

"""Interpretasi Grafik
Distribution of Restock Quantity

Grafik ini menunjukkan distribusi jumlah restock yang dibutuhkan per SKU, berdasarkan hasil inventory optimization.

Sumbu X → jumlah unit yang perlu direstock

Sumbu Y → jumlah SKU

Histogram + kurva → pola sebaran kebutuhan restock

Distribusi kebutuhan restock menunjukkan bahwa sebagian besar SKU tidak membutuhkan tindakan segera, sementara risiko bisnis justru terkonsentrasi pada segelintir SKU dengan kebutuhan restock tinggi. Dengan pendekatan prioritas berbasis data, perusahaan dapat mengoptimalkan cashflow tanpa mengorbankan service level.

🔎 Temuan Utama (Key Observations)
1️⃣ Distribusi sangat right-skewed (miring ke kanan)

Mayoritas SKU:

Kebutuhan restock sangat kecil atau nol

Sebagian kecil SKU:

Memiliki restock quantity sangat besar

👉 Ini adalah pola Pareto / 80–20 yang sangat umum di inventory.

2️⃣ Banyak SKU tidak perlu restock

Puncak histogram di dekat 0

Artinya:

Stok saat ini masih aman

Atau demand rendah (slow/dead stock)

📌 Ini penting karena:

Tidak semua SKU butuh tindakan → fokus bisa dipersempit

3️⃣ Ekor kanan = SKU kritis

SKU di area kanan (mis. >100 unit):

FAST moving

Stok jauh di bawah reorder point

Risiko:

Stock-out

Lost sales

Customer dissatisfaction
"""

# FORECAST + REORDER POINT
plot_inventory(
    temp=temp,
    future_dates=future_dates,
    forecast=forecast,
    inventory=inventory,
    product_name=product_name
)